### ISSUE TITLE
Arg order in <^> vs >>-

### ISSUE THREAD

**Issue by refried** [typelift/swiftz#152]
Is there a reason why <^> and >>- don't take their args in the same order?  Should one of them be switched (eg <^>) or do you recommend using the map method directly in that case?

Thanks!

**Comment by CodaFi** [comment]
@refried  Any further input, or has this thread run its course?

**Comment by refried** [comment]
Oh hello :)

Well, to be honest, I was left with the feeling that I wasn't able to get
my point across at all. Is that something you'd be interested in still?

**Comment by CodaFi** [comment]
Then let's start over.

Restate the question and I'll try to be more succinct about replying this time.

**Comment by refried** [comment]
Thanks -- I guess to start, could you show a working Swift example of the
anticipated use case for <^>? (hopefully including composition?)

**Comment by CodaFi** [comment]
[UserExample.swift](https://github.com/typelift/swiftz/blob/master/swiftzTests/UserExample.swift) has a pretty good example of using `<^>`

```Swift
public class func fromJSON(x: JSONValue) -> User? {
	var n: String?
	var a: Int?
	var t: [String]?
	var r: Dictionary<String, String>?
	switch x {
	case let .JSONObject(d):
		n = d["name"]   >>- JString.fromJSON
		a = d["age"]    >>- JInt.fromJSON
		t = d["tweets"] >>- JArray<String, JString>.fromJSON
		r = d["attrs"]  >>- JDictionary<String, JString>.fromJSON
		// alternatively, if n && a && t... { return User(n!, a!, ...
		return (User.create <^> n <*> a <*> t <*> r)
	default:
		return .None
	}
}
```

If you're asking for something like `fmap • fmap • fmap` I'll refer you [here](http://stackoverflow.com/a/23030781/945847).

**Comment by refried** [comment]
Thanks -- that is certainly a different use case than I expected: producing a partially applied lifted function.  Is that the expected use case?

The second link you sent was in Haskell though, so it didn't answer my question about Swift at all.

**Comment by CodaFi** [comment]
The reason I continue to bring up Haskell is that as a language it has a beautiful and straightforward approach to laying out the kinds of abstractions we're using here.  Our work stems from that, and our semantics does the same.

**Comment by refried** [comment]
I understand that, but it doesn't help. My question was about Swiftz, which
I'm assuming only exists at all due to the fact that Swift is not the same
thing as Haskell.

**Comment by CodaFi** [comment]
This is one of those cases where semantics transcends language boundaries.

________

But an example in Swift is an easy thing to produce.  The interpretation of a Functor that we take (because we're restricted to the Category of Swift Types- hereafter $) is an Endofunctor- or a Functor that maps the same domain to the same range (`$ -> $`).  The members of the category `$` are any valid Swift structure, protocol, and class, the arrows are the free and member functions that map them between each other.  Because we're restricted to Endomorphic behaviour, our fmap must take Functors over one Swift type to Functors over other Swift types.  Such a function looks like this:

```swift
func fmap<T, U>(f : T -> U, fun : Functor<T>) -> Functor<U>
```

which is curried as:

```swift
func fmap<T, U>(f : T -> U) -> Functor<T> -> Functor<U>
```

> Is there a reason why <^> and >>- don't take their args in the same order? Should one of them be switched (eg <^>)

Take a look at that type signature one more time.  

```swift
(T -> U) -> F<T> -> F<U>
```

Notice anything special about the last half of the function?

```swift
(T -> U) -> (F<T> -> F<U>)
```

fmap is lifting a function to a function over Functors.  It is not binding data, it's lifting functions.  The function is the most important part of the type signature, and so we keep it as such.

________________

> Thanks -- that is certainly a different use case than I expected: producing a partially applied lifted function. Is that the expected use case?

Yes and no.  Yes in the sense of the wall of text I just posted.  No in the sense that because we can't actually use Functors in general because of Swift's type system, we instead use the protocol Functor to mark structures that can map themselves over to different types.  We define a large amount of those structures that perhaps overload Functor to perform a little more than lifting (JSON stuff mostly).  Ultimately they all accomplish the same thing: Lifting a function to a function over a Functor.

**Comment by refried** [comment]
I guess I must not be smart enough to know how to ask a question that you
can understand and answer in such a way that it is recognizable as an
answer to my question.  Thanks anyway!

**Comment by CodaFi** [comment]
I'm a chronic overthinker :(

If you think of a way to reformulate this question, reopen this issue.

**Comment by refried** [comment]
I read your answer again this morning, just wanted to add a quick note to say that even though I don't feel that it answers my question, it was informative and interesting.  So thanks for now!

**Comment by refried** [comment]
If you flip the types around, you get:
```
F<A> -> (A -> B) -> (B -> C) -> ... -> (Y -> Z) -> F<Z>
```
How would you do that instead now?  Thanks!

**Comment by refried** [comment]
You has previously pointed out that
```
(f <^>) • (g <^>) = ((f • g) <^>)
```
but is there an example in swift?

**Comment by CodaFi** [comment]
> I read your answer again this morning, just wanted to add a quick note to say that even though I don't feel that it answers my question, it was informative and interesting. So thanks for now! 

You're very welcome.  I'm terribly sorry I'm incapable of grokking your question right now.  I don't want this to wind up as a situation where you get turned off by jargon, or feel like FP means I can't help you.  You're absolutely "smart enough" to ask questions around here!

________________

> If you flip the types around, you get:
> F<A> -> (A -> B) -> (B -> C) -> ... -> (Y -> Z) -> F<Z>
> How would you do that instead now? Thanks!

Short Answer: 

```swift
flip(<^>)
```

Long Answer: 

By virtue of our definition of Functor we already give you an fmap that looks like

```swift
F<A> -> (A -> B) -> F<B>

public protocol Functor {
	/// ...
	/// Map a function over the value encapsulated by the Functor.
	func fmap(f : A -> B) -> FB
}
```

Though it may not look like it, Every member function in Swift actually looks like this internally:

```swift
struct Foo<A> : Functor {
    func fmap(f : A -> B) -> Foo<B> { // do stuff }
}

fmap : Foo<A> -> (A -> B) -> Foo<B>
```

but you have to invoke it statically (`Foo<A>.fmap` rather than `Foo<A>().fmap`) to see that.  By yet another virtue, this time of the language, `.` to invoke functions can be used to compose `fmap`s rather than `•` like function composition.

> You has previously pointed out that
> (f <^>) • (g <^>) = ((f • g) <^>)
> but is there an example in swift?

Yes!  I'll show you with the Identity Functor (Box) out of laziness.  Throw this in a playground

```
// --------- Prerequisites ----------- //
public class K1<A> {}

infix operator • {}

public func •<A, B, C>(f: B -> C, g: A -> B) -> A -> C {
	return { (a: A) -> C in
		return f(g(a))
	}
}


public protocol Functor {
	/// Source
	typealias A
	/// Target
	typealias B
	/// A Target Functor
	typealias FB = K1<B>

	/// Map a function over the value encapsulated by the Functor.
	func fmap(f : A -> B) -> FB
}


/// The Identity Functor holds a singular value.
public struct Id<A> {
	private let a : @autoclosure () -> A

	public init(_ aa : A) {
		a = aa
	}

	public var runId : A {
		return a()
	}
}

extension Id : Functor {
	public typealias B = Any

	public func fmap<B>(f : A -> B) -> Id<B> {
		return (Id<B>(f(self.runId)))
	}
}

//--------------!!--------------//

let id = Id<Int>(5)
let f : Int -> Int = { x in x + 5 }
let g : Int -> String = { x in String(x) }

let x = id.fmap(f).fmap(g).runId // String("10")
let y = id.fmap(g • f).runId // String("10")

x == y // true
```

**Comment by refried** [comment]
Does swiftz include an fmap implementation for every <^> implementation?
(since AFAIK, swift won't let us share one single definition)

**Comment by CodaFi** [comment]
(Unfortunately for my poor fingers) Yes.  We have to write an fmap for every Functor.

**Comment by refried** [comment]
:)
