### ISSUE TITLE
Will CocoaPods be supported?

### ISSUE THREAD

**Issue by etartakovsky** [typelift/Swiftz#316]
# Environment

Mac OS X / iOS

**Comment by CodaFi** [comment]
CocoaPods will be supported when they fix the bug that rewrites repository origins.  Until then I can't trust them to build this package or any other under this organization.  If that is the case and I missed something please submit a pull request that uncomments this line: https://github.com/typelift/Swiftz/blob/master/.travis.yml#L13

**Comment by Flar49** [comment]
Thanks. 

Unfortunately, I'm not aware of the bug. Based on what i was able to google:
Looks like similar issue: https://github.com/CocoaPods/CocoaPods/issues/5828
Which should be fixed as part of https://github.com/CocoaPods/CocoaPods/pull/5822
And released in 1.1.0.rc.1

This comment states that the bug was fixed in 1.1.0.rc.2: https://github.com/CocoaPods/CocoaPods/issues/5828#issuecomment-250965249

Here is the latest release which should work correctly: https://github.com/CocoaPods/CocoaPods/releases/tag/1.1.0.rc.3

Can you please verify whether the bug is fixed in 1.1.0.rc.3 and enable cocoapods back if it is so?

**Comment by yurrriq** [comment]
:+1:

**Comment by CodaFi** [comment]
0.6.3 was just pushed to trunk.

**Comment by yurrriq** [comment]
Works for me, thanks!
